Install recoil, create apiKeys state and selector, spelling mistakes. Delete apiKey context
dg1886/crypto_tables_app pull request #39
Opened 2022-09-27 07:17 UTC by dg1886

2022-09-27 09:10 UTC, neko-peko requested changes

2022-09-27 09:10 UTC, neko-peko commented on src/state/selectors/apiKeysSelectors.js
> +    return get(apiKeysState);
Не лучше ли сразу сделать селектор, который вам каждый раз отдаёт разные ключи? По-идее это и должно проходить здесь. Называется даже "selector"

2022-09-28 09:08 UTC, dg1886 commented on src/state/selectors/apiKeysSelectors.js
> +  },
Я не уверен корректна ли такая конструкция, но я правда чуть не поседел заставляя это работатью

2022-09-28 11:34 UTC, neko-peko approved these changes

2022-09-28 11:58 UTC, merged